name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        echo node version is `node -v`
        yarn

    - name: Build Vue App
      run: |
        yarn build
    # - name: Create and Push to New Branch
    #   run: |
    #     git config --global user.email "272905918@qq.com"
    #     git config --global user.name "ACTION BOT"
    #     # Create a new branch (replace new-branch-name with your desired branch name)
    #     git checkout -b artifact
    #     # Add and commit the changes
    #     git add .
    #     git commit -m "Add build artifacts"
    #     # Push to the new branch
    #     git push origin artifact
 
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Vue 项目的构建输出目录
